version: "3"
services:
  web:
    image: corenzan/wordpress
    networks:
      - default
      - traefik
    volumes:
      - .:/var/www/localhost/htdocs
    environment:
      - DATABASE_URL=mysql://root:123@db/wordpress
      - REMOTE_URL=https://example.org
      - WP_DEBUG=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`wordpress.localhost`)
  db:
    image: mariadb:10.3
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=123
networks:
  traefik:
    external: true
