version: "3"
services:
  web:
    image: haggen/wordpress:apache
    depends_on:
      - db
    ports:
      - 80
    volumes:
      - .:/var/www/localhost/htdocs
    working_dir: /var/www/localhost/htdocs
    environment:
      - VIRTUAL_HOST=wordpress.localhost
      - DATABASE_URL=mysql://root:123@db/wordpress
      - UPLOADS_URL=
      - WP_DEBUG=true
  db:
    image: mariadb:10
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=123
